// Shared agent prompt files + per-project workspace memory.
// Mirrors Get-SharedPromptContent (ps1:2185), Sync-SharedAgentFiles (ps1:2213),
// Get-WorkspaceId (ps1:1966), Sync-WorkspacePromptFiles (ps1:2006) and
// Initialize-WorkspaceMemory (ps1:2031).
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { crossAgnetCodingHome } from './platform.mjs';
import { ensureDir, readText } from './util.mjs';

// The cross-agent context written into every shared/workspace prompt file.
export function sharedPromptContent() {
  return `# CrossAgnetCoding Shared Agent Context

Use AgentMemory for durable cross-agent context.

AgentMemory MCP endpoint:
http://localhost:3111

Recommended workflow:
1. At task start, search AgentMemory for project goals, decisions, and active constraints.
2. During work, store durable decisions, file paths, test commands, and cross-agent handoff notes.
3. At task end, summarize what changed and write a concise memory entry.

This file is generated by CrossAgnetCoding and inspired by cc-switch style shared agent configuration.
`;
}

// Write the shared prompt to the per-agent files under <home>/shared/.
export function syncSharedAgentFiles() {
  const sharedDir = path.join(crossAgnetCodingHome(), 'shared');
  ensureDir(sharedDir);
  const content = sharedPromptContent();
  const names = ['AGENTS.md', 'CLAUDE.md', 'OPENCODE.md', 'TRAE.md', 'GEMINI.md', 'OPENCLAW.md', 'HERMES.md'];
  const paths = [];
  for (const name of names) {
    const p = path.join(sharedDir, name);
    fs.writeFileSync(p, content, 'utf8');
    paths.push(p);
  }
  return paths;
}

// Lowercased `git -C <dir> config --get remote.origin.url`, or "" when not a
// git repo / git missing (mirrors Get-ProjectGitRemote).
function projectGitRemote(projectPath) {
  try {
    const r = spawnSync('git', ['-C', projectPath, 'config', '--get', 'remote.origin.url'], {
      encoding: 'utf8',
    });
    if (r.status === 0 && r.stdout && r.stdout.trim()) return r.stdout.trim().toLowerCase();
  } catch {
    // git unavailable
  }
  return '';
}

// Stable 16-hex workspace id: sha256 of the normalized project path, plus the
// git remote when present (mirrors Get-WorkspaceId).
export function workspaceId(projectPath) {
  const full = path.resolve(projectPath || process.cwd());
  const normalized = full.replace(/[/\\]+$/, '').toLowerCase();
  const remote = projectGitRemote(full);
  const identity = remote ? `${normalized}|${remote}` : normalized;
  return crypto.createHash('sha256').update(identity, 'utf8').digest('hex').slice(0, 16);
}

export function workspacePath(projectPath) {
  return path.join(crossAgnetCodingHome(), 'workspaces', workspaceId(projectPath));
}

function workspacePromptFileNames() {
  return ['AGENTS.md', 'TRAE.md', 'CLAUDE.md', 'GEMINI.md', 'OPENCODE.md', 'OPENCLAW.md', 'HERMES.md'];
}

// Refresh the per-workspace prompt files (shared context + project + latest
// handoff). Returns the written paths.
export function syncWorkspacePromptFiles(projectPath) {
  const full = path.resolve(projectPath);
  const wsPath = workspacePath(full);
  ensureDir(wsPath);

  const handoff = readText(path.join(wsPath, 'handoff.md'));
  const content =
    sharedPromptContent() +
    `\n\n## Workspace\nProject: ${full}\nWorkspace ID: ${workspaceId(full)}\n\n## Latest Handoff\n${handoff}`;

  const paths = [];
  for (const name of workspacePromptFileNames()) {
    const p = path.join(wsPath, name);
    fs.writeFileSync(p, content, 'utf8');
    paths.push(p);
  }
  return paths;
}

// Create/refresh the workspace memory for a project: workspace.json + prompt
// files (mirrors Initialize-WorkspaceMemory). Returns descriptive paths.
export function initializeWorkspaceMemory(projectPath) {
  const full = path.resolve(projectPath || process.cwd());
  const wsPath = workspacePath(full);
  ensureDir(wsPath);

  const now = new Date().toISOString();
  const workspaceFile = path.join(wsPath, 'workspace.json');
  let createdAt = now;
  if (fs.existsSync(workspaceFile)) {
    try {
      const existing = JSON.parse(fs.readFileSync(workspaceFile, 'utf8'));
      if (existing && existing.createdAt) createdAt = existing.createdAt;
    } catch {
      // keep `now`
    }
  }

  const workspace = { id: workspaceId(full), projectPath: full, createdAt, updatedAt: now };
  fs.writeFileSync(workspaceFile, JSON.stringify(workspace, null, 2) + '\n', 'utf8');
  syncWorkspacePromptFiles(full);

  return { id: workspace.id, projectPath: full, workspacePath: wsPath, workspaceFile };
}
